In [2]:
import tensorflow as tf
from tensorflow.keras import preprocessing

In [3]:
samples = ['너 오늘 이뻐 보인다',
          '나는 오늘 기분이 더러워',
          '끝내주는데, 좋은 일이 있나봐',
          '나 좋은 일이 생겼어',
          '아 오늘 진짜 짜증나',
          '환상적인데, 정말 좋은거 같아']

targets =[[1], [0], [1], [1], [0], [1]]

In [6]:
import numpy as np

In [10]:
tokenizer = preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples)
print(sequences)
input_sequences = np.array(sequences)
print(input_sequences)
labels = np.array(targets)
print(labels)
word_index = tokenizer.word_index
print(word_index)

[[4, 1, 5, 6], [7, 1, 8, 9], [10, 2, 3, 11], [12, 2, 3, 13], [14, 1, 15, 16], [17, 18, 19, 20]]
[[ 4  1  5  6]
 [ 7  1  8  9]
 [10  2  3 11]
 [12  2  3 13]
 [14  1 15 16]
 [17 18 19 20]]
[[1]
 [0]
 [1]
 [1]
 [0]
 [1]]
{'오늘': 1, '좋은': 2, '일이': 3, '너': 4, '이뻐': 5, '보인다': 6, '나는': 7, '기분이': 8, '더러워': 9, '끝내주는데': 10, '있나봐': 11, '나': 12, '생겼어': 13, '아': 14, '진짜': 15, '짜증나': 16, '환상적인데': 17, '정말': 18, '좋은거': 19, '같아': 20}


batch_size = 2                       : 2개의 문장을 입력받을 때 마다, 가중치 업데이트\
num_epochs = 100                     : 총6개의 문장을 받아오는데 이걸 100번\
vocab_size = len(word_index) + 1     : word_index라는 사전에 20개의 단어가 존재한다. but 0부터 시작하면 19에서 끝나므로, 1부터 시작하게 +1 더함\
emb_size = 128                       : 각 단어의 임베딩 사이즈 : 128 차원의 임베딩으로 만든다\
hidden_dimension = 256               : FC로 연결되는 내부 은닉층 노드 개수\
output_dimension = 1                 : 출력 1차원 => 0 or 1

In [12]:
from keras import layers

In [14]:
batch_size = 2
num_epochs = 100
vocab_size = len(word_index) + 1
emb_size = 128
hidden_dimension = 256
output_dimension = 1

In [15]:
model = tf.keras.Sequential([
layers.Embedding(vocab_size, emb_size, input_length = 4),
layers.Lambda(lambda x: tf.reduce_mean(x, axis = 1)),
layers.Dense(hidden_dimension, activation='relu'),
layers.Dense(output_dimension, activation='sigmoid')])

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 128)            2688      
                                                                 
 lambda (Lambda)             (None, 128)               0         
                                                                 
 dense (Dense)               (None, 256)               33024     
                                                                 
 dense_1 (Dense)             (None, 1)                 257       
                                                                 
Total params: 35,969
Trainable params: 35,969
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.fit(input_sequences, labels, epochs=num_epochs, batch_size=batch_size)

Epoch 1/100
3/3 [==============================] - 1s 5ms/step - loss: 0.6886 - accuracy: 0.8333
Epoch 2/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6700 - accuracy: 1.0000
Epoch 3/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6539 - accuracy: 1.0000
Epoch 4/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6350 - accuracy: 1.0000
Epoch 5/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6165 - accuracy: 1.0000
Epoch 6/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5936 - accuracy: 1.0000
Epoch 7/100
3/3 [==============================] - 0s 8ms/step - loss: 0.5656 - accuracy: 1.0000
Epoch 8/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5360 - accuracy: 1.0000
Epoch 9/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5033 - accuracy: 1.0000
Epoch 10/100
3/3 [==============================] - 0s 3ms/step - loss: 0.4644 - accuracy: 1.0000
Epoch 11/100
3/3 [===========

In [22]:
test=["나 진짜 오늘 짜증나"]
seq=tokenizer.texts_to_sequences(test)
print(seq)

[[12, 15, 1, 16]]


In [23]:
model.predict(seq)

array([[0.02005178]], dtype=float32)

In [24]:
test=["나 진짜 오늘 이뻐"]
seq=tokenizer.texts_to_sequences(test)
print(seq)

[[12, 15, 1, 5]]


In [25]:
model.predict(seq)

array([[0.8309136]], dtype=float32)