<a href="https://colab.research.google.com/github/DonghaeSuh/NLP_tensorflow2/blob/main/layer_dot().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.layers import dot

In [2]:
import numpy as np

In [3]:
a=np.arange(2*3*5).reshape(2,3,5)
b=np.arange(2*1*5).reshape(2,1,5)

In [4]:
print(a)
print(b)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[0 1 2 3 4]]

 [[5 6 7 8 9]]]


In [5]:
c=dot([a,b],axes=-1)
print(c)

tf.Tensor(
[[[ 30]
  [ 80]
  [130]]

 [[605]
  [780]
  [955]]], shape=(2, 3, 1), dtype=int64)


In [6]:
x = np.arange(10).reshape(1, 5, 2)
print(x)

y = np.arange(10, 20).reshape(1, 2, 5)
print(y)

c=dot([x, y],axes=(1, 2))
print(c)

[[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]]
[[[10 11 12 13 14]
  [15 16 17 18 19]]]
tf.Tensor(
[[[260 360]
  [320 445]]], shape=(1, 2, 2), dtype=int64)


In [7]:
x = np.arange(10).reshape(1, 5, 2)
print(x)

y = np.arange(10, 20).reshape(1, 2, 5)
print(y)

c=dot([x, y],axes=(1,2))
print(c)

[[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]]
[[[10 11 12 13 14]
  [15 16 17 18 19]]]
tf.Tensor(
[[[260 360]
  [320 445]]], shape=(1, 2, 2), dtype=int64)


In [8]:
x = np.arange(10).reshape(1, 5, 2)
print(x)

y = np.arange(10, 20).reshape(1, 2, 5)
print(y)

c=dot([x, y],axes=(2,1))
print(c)

[[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]]
[[[10 11 12 13 14]
  [15 16 17 18 19]]]
tf.Tensor(
[[[ 15  16  17  18  19]
  [ 65  70  75  80  85]
  [115 124 133 142 151]
  [165 178 191 204 217]
  [215 232 249 266 283]]], shape=(1, 5, 5), dtype=int64)
