<a href="https://colab.research.google.com/github/DonghaeSuh/NLP_tensorflow2/blob/main/np_sum().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## numpy .sum()

In [1]:
import numpy as np

In [2]:
a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])

In [8]:
c=np.stack((a,b),axis=0) #aixs=-3
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
c.sum(axis=0)

array([[ 6,  8],
       [10, 12]])

In [11]:
c.sum(axis=1)

array([[ 4,  6],
       [12, 14]])

In [12]:
c.sum(axis=2)

array([[ 3,  7],
       [11, 15]])