<a href="https://colab.research.google.com/github/DonghaeSuh/NLP_tensorflow2/blob/main/np_stack().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])

In [4]:
c=np.stack((a,b),axis=0) #axis=-3
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
c=np.stack((a,b),axis=1) #axis=-2
c

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [6]:
c=np.stack((a,b),axis=2) #axis=-1
c

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])