<a href="https://colab.research.google.com/github/DonghaeSuh/NLP_tensorflow2/blob/main/0_Test/numpy_tool/numpy_matrix_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 하나의 벡터에 대해 여러개의 벡터와의 연산(덧셈,뺄셈,곱셈,나눗셈)을 하고 싶을 경우

행렬이 존재하는 특정 차원에서\
크기가 다른 두 행렬 연산을 진행하게 되면\
연산이 진행된 차원에 그 행렬들이 담기게 된다.\
즉, 껍대기를 건들지 않고 내부에서 처리할 수 있다는 뜻


크기가 다른 두 행렬의 연산의 결과는
큰 차원의 크기에 맞춰진다.\
ex) (1x3) + (4x3) = (4x3)\
ex) (2x3) + (5x3) = (5x3) 

In [3]:
a=np.array([[[1,2,3],[4,5,6]]])
b=np.array([[[7,8,9]],[[10,11,12]],[[13,14,15]]])
print(a)
print(b)
print(a.shape)
print(b.shape)
print(a+b)

[[[1 2 3]
  [4 5 6]]]
[[[ 7  8  9]]

 [[10 11 12]]

 [[13 14 15]]]
(1, 2, 3)
(3, 1, 3)
[[[ 8 10 12]
  [11 13 15]]

 [[11 13 15]
  [14 16 18]]

 [[14 16 18]
  [17 19 21]]]


In [6]:
print(a*b)

[[[ 7 16 27]
  [28 40 54]]

 [[10 22 36]
  [40 55 72]]

 [[13 28 45]
  [52 70 90]]]


In [7]:
a=np.array([[[1,2,3],[4,5,6]]])
b=np.array([[[7,8,9],[1,1,1]],[[10,11,12],[2,2,2]],[[13,14,15],[3,3,3]]])
print(a)
print(b)
print(a.shape)
print(b.shape)
print(a+b)

[[[1 2 3]
  [4 5 6]]]
[[[ 7  8  9]
  [ 1  1  1]]

 [[10 11 12]
  [ 2  2  2]]

 [[13 14 15]
  [ 3  3  3]]]
(1, 2, 3)
(3, 2, 3)
[[[ 8 10 12]
  [ 5  6  7]]

 [[11 13 15]
  [ 6  7  8]]

 [[14 16 18]
  [ 7  8  9]]]
