<a href="https://colab.research.google.com/github/DonghaeSuh/NLP_tensorflow2/blob/main/tf_reduce_sum().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [7]:
x = tf.constant([[[1, 2, 3], [4, 5, 6]],[[7,8,9],[10,11,12]]])
x

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [8]:
tf.reduce_sum(x).numpy()

78

In [9]:
tf.reduce_sum(x, 0).numpy()

array([[ 8, 10, 12],
       [14, 16, 18]], dtype=int32)

In [10]:
tf.reduce_sum(x, 1).numpy()

array([[ 5,  7,  9],
       [17, 19, 21]], dtype=int32)

In [11]:
tf.reduce_sum(x, 2).numpy()

array([[ 6, 15],
       [24, 33]], dtype=int32)