<a href="https://colab.research.google.com/github/DonghaeSuh/NLP_tensorflow2/blob/main/0_Test/numpy_tool/tf_transpose_perm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### tf.reshape & tf.transpose  (4차원)

In [1]:
import numpy as np
import tensorflow as tf

In [ ]:
a = np.array([[[1,2,3,4],[4,5,6,7]],[[7,8,9,10],[10,11,12,13]]])
a

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7]],

       [[ 7,  8,  9, 10],
        [10, 11, 12, 13]]])

In [ ]:
b=tf.reshape(a,(2,-1,2,2))
b

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 7,  8],
         [ 9, 10]],

        [[10, 11],
         [12, 13]]]])>

In [ ]:
tf.transpose(b) # perm = [3,2,1,0]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  7],
         [ 4, 10]],

        [[ 3,  9],
         [ 6, 12]]],


       [[[ 2,  8],
         [ 5, 11]],

        [[ 4, 10],
         [ 7, 13]]]])>

In [ ]:
tf.transpose(b,[0,2,1,3])

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  2],
         [ 4,  5]],

        [[ 3,  4],
         [ 6,  7]]],


       [[[ 7,  8],
         [10, 11]],

        [[ 9, 10],
         [12, 13]]]])>

In [ ]:
tf.transpose(b,[3,1,2,0])

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  7],
         [ 3,  9]],

        [[ 4, 10],
         [ 6, 12]]],


       [[[ 2,  8],
         [ 4, 10]],

        [[ 5, 11],
         [ 7, 13]]]])>

In [ ]:
tf.reshape(a,(2,2,-1,2))

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 7,  8],
         [ 9, 10]],

        [[10, 11],
         [12, 13]]]])>

----------

In [ ]:
x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])

In [ ]:
x

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
tf.transpose(x) #perm=[2,1,0]

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]], dtype=int32)>

In [ ]:
tf.transpose(x,perm=[1,2,0])

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]], dtype=int32)>

In [ ]:
tf.transpose(x,perm=[2,0,1])

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  4],
        [ 7, 10]],

       [[ 2,  5],
        [ 8, 11]],

       [[ 3,  6],
        [ 9, 12]]], dtype=int32)>

-------

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
tf.transpose(a) # perm = [1,0]

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>