<a href="https://colab.research.google.com/github/DonghaeSuh/NLP_tensorflow2/blob/main/layers_add()%26layers_Activation().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from keras.layers import dot

In [10]:
from keras.layers import add 

In [2]:
import numpy as np

In [17]:
a= np.arange(2*3*2).reshape(2,3,2)
b=np.arange(10,10+2*2*2).reshape(2,2,2)
print(a)
print(b)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]]


In [11]:
c=add([a,b])
print(c)

tf.Tensor(
[[[10 12]
  [14 16]]

 [[18 20]
  [22 24]]], shape=(2, 2, 2), dtype=int64)


In [4]:
from tensorflow.keras.layers import Permute

In [23]:
a.shape

(2, 3, 2)

In [24]:
d = Permute((2,1))(a)
print(d)

tf.Tensor(
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]], shape=(2, 2, 3), dtype=int64)


In [34]:
from keras.layers import Concatenate

In [42]:
x = np.arange(20).reshape(2, 2, 5)
print(x)




y = np.arange(20, 40).reshape(2, 2, 5)
print(y)


a=Concatenate()([x, y])
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
[[[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]]
tf.Tensor(
[[[ 0  1  2  3  4 20 21 22 23 24]
  [ 5  6  7  8  9 25 26 27 28 29]]

 [[10 11 12 13 14 30 31 32 33 34]
  [15 16 17 18 19 35 36 37 38 39]]], shape=(2, 2, 10), dtype=int64)


In [46]:
from keras.layers import Input

In [50]:
input_sequence = Input((3,))
question = Input((4,))

print('Stories :', input_sequence)
print('Question:', question)
print([input_sequence,question])

Stories : KerasTensor(type_spec=TensorSpec(shape=(None, 3), dtype=tf.float32, name='input_7'), name='input_7', description="created by layer 'input_7'")
Question: KerasTensor(type_spec=TensorSpec(shape=(None, 4), dtype=tf.float32, name='input_8'), name='input_8', description="created by layer 'input_8'")
<class 'list'>


In [1]:
from tensorflow.keras.layers import Activation

In [7]:
match =np.random.rand(2,2,5)
match

array([[[0.45812061, 0.83440952, 0.79632706, 0.55983681, 0.1319241 ],
        [0.93227291, 0.16807308, 0.40176262, 0.04732638, 0.1209312 ]],

       [[0.45985305, 0.31831205, 0.29154811, 0.23610657, 0.14003098],
        [0.59284622, 0.59325206, 0.99954747, 0.57707352, 0.3470448 ]]])

In [8]:
match = Activation('softmax')(match)
print('Match shape', match)

Match shape tf.Tensor(
[[[0.17580777 0.25612873 0.2465581  0.19463138 0.12687403]
  [0.34352353 0.15998112 0.2020965  0.14178461 0.15261431]]

 [[0.23590961 0.20477416 0.1993663  0.18861394 0.17133602]
  [0.1898005  0.18987754 0.2850529  0.18683033 0.1484387 ]]], shape=(2, 2, 5), dtype=float32)


In [16]:
ex=np.array(match)

In [17]:
ex.sum(axis=-1)

array([[1.        , 1.0000001 ],
       [1.        , 0.99999994]], dtype=float32)