<a href="https://colab.research.google.com/github/DonghaeSuh/NLP_tensorflow2/blob/main/layer_dot().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.layers import dot

In [2]:
import numpy as np

In [13]:
a=np.arange(2*3*5).reshape(2,3,5)
b=np.arange(2*1*5).reshape(2,1,5)
c=np.arange(2*2*5).reshape(2,2,5)

In [14]:
print(a)
print(b)
print(c)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[0 1 2 3 4]]

 [[5 6 7 8 9]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [15]:
d=dot([a,b],axes=-1)
print(d)

tf.Tensor(
[[[ 30]
  [ 80]
  [130]]

 [[605]
  [780]
  [955]]], shape=(2, 3, 1), dtype=int64)


In [16]:
d=dot([a,c],axes=-1)
print(d)

tf.Tensor(
[[[  30   80]
  [  80  255]
  [ 130  430]]

 [[1030 1455]
  [1330 1880]
  [1630 2305]]], shape=(2, 3, 2), dtype=int64)


In [22]:
x = np.arange(2*3*2).reshape(2,3,2)
print(x)

y = np.arange(2*2*3).reshape(2, 2, 3)
print(y)

c=dot([x, y],axes=(1, 2))
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
tf.Tensor(
[[[ 10  28]
  [ 13  40]]

 [[172 244]
  [193 274]]], shape=(2, 2, 2), dtype=int64)


In [23]:
x = np.arange(2*3*2).reshape(2,3,2)
print(x)

y = np.arange(2*2*3).reshape(2, 2, 3)
print(y)

c=dot([x, y],axes=(2, 1))
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
tf.Tensor(
[[[  3   4   5]
  [  9  14  19]
  [ 15  24  33]]

 [[ 99 112 125]
  [129 146 163]
  [159 180 201]]], shape=(2, 3, 3), dtype=int64)
