## 넘파이 배열

1. ndarray.ndim : 배열의 축(차원)의 수를 반환
2. ndarray.shape() : 배열의 형태를 반환 ex)2x3크기의 2차원 배열 => shape()= (2,3)
3. ndarray.size() : 배열 내 원소의 총 개수를 반환
4. ndarray.dtype() : 배열 내 원소들의 자료형을 반환

In [1]:
import numpy as np

In [4]:
a = np.array([[1,2,3], [1,5,9], [3,5,7]])
print(a)
print(a.ndim)  
print(a.shape) 
print(a.size) 
print(a.dtype) 

[[1 2 3]
 [1 5 9]
 [3 5 7]]
2
(3, 3)
9
int32


## 다양한 배열 생성 방법

1. numpy.zeros : 모든 배열의 원소가 0인 배열 생성
2. numpy.ones  : 모든 배열의 원소가 1인 배열 생성
3. numpy.empty : 배열의 크기만 정해주고 원소는 초기화 하지 않은 배열 생성. 원소는 매우 크거나 작은값 부여
4. numpy.arange : 파이썬의 range함수와 유사. 배열의 원소들이 수열을 구성
5. numpy.full  : 배열의 모든 값이 하나의 상수인 배열 생성
6. numpy.eye               : 지정한 크기의 단위행렬 생성
7. numpy.random.random     : 배열의 원소를 임의의 값으로 생성 (0부터 1사이의 값)

In [5]:
a = np.zeros((2,3)) #원소가 모두 0인 배열 생성
print(a)      

b = np.ones((2,1)) #원소가 모두 1인 배열 생성
print(b)      

c = np.empty((2,2)) #원소값을 초기화하지 않은 배열 생성
print(c)      



d = np.arange(10, 30, 5) # 10부터 30전 까지 5단위로 배열 생성
print(d)      



e = np.full((2, 2), 4) #원소가 모두 4인 배열 생성
print(e)      



f = np.eye(3) # 3x3 크기의 단위행렬 생성
print(f)      


g = np.random.random((2, 2)) # 임의값을 가지는 배열 생성
print(g)      


[[0. 0. 0.]
 [0. 0. 0.]]
[[1.]
 [1.]]
[[1.17025243e-311 6.01334637e-154]
 [1.05132387e-153 5.98147409e-154]]
[10 15 20 25]
[[4 4]
 [4 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.89189585 0.68873932]
 [0.15037302 0.93146173]]


In [7]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a+b)                     
print()
print(np.add(a,b)) # 위의 연산과 같다.        
print()
print(b-a)                      
print()
print(np.subtract(b,a)) # 위의 연산과 같다.
print()
print(a**2)                   
print()

print(b<15)                   
print()

C = np.array([[1, 2],
              [3, 4]])
print()
D = np.array([[10, 20],
              [30, 10]])
print()
print(C*D)  # 원소별 곱셈
print()

print(np.dot(C,D)) # 내적(dot product) 계산 (행렬이므로 행렬곱)
print()

print(C.dot(D)) #내적의 또 다른 사용법
print()

[11 22 33]

[11 22 33]

[ 9 18 27]

[ 9 18 27]

[1 4 9]

[ True False False]



[[10 40]
 [90 40]]

[[ 70  40]
 [150 100]]

[[ 70  40]
 [150 100]]



In [8]:
a = np.array([[ 1, 2, 3, 4],
              [ 5, 6, 7, 8],
              [ 1, 3, 5, 7]])

print(a.sum(axis=0)) # 0축, 즉 열을 기준으로한 덧셈


print(a.sum(axis=1)) # 1축, 즉 행을 기준으로한 덧셈



print(a.max(axis=1)) # 각 행에서의 최대값


[ 7 11 15 19]
[10 26 16]
[4 8 7]


In [9]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

print(a[3]) 



print(a[-1]) # 마지막 원소


print(a[2: 5]) # 인덱스값 5를 가지는 원소 전까지


print(a[2: ])


print(a[ :4])


4
7
[3 4 5]
[3 4 5 6 7]
[1 2 3 4]


In [10]:
a = np.array([[ 1, 2, 3],
              [ 4, 5, 6],
              [ 7, 8, 9]])


print(a[1, 2])


print(a[ : , 1]) # 1열의 모든 원소


print(a[-1]) # 마지막 행

6
[2 5 8]
[7 8 9]


1. ndarray.ravel() : 배열을 1차원 배열로 만듬
2. ndarray.reshape() : 배열을 원하는 형태로 변환
3. ndarray.T : 행렬 전치

In [11]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])

print(a.ravel()) # 1차원 배열(벡터)로 만들어준다.


print(a.reshape(2, 6))



print(a.T)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [12]:
print(a.reshape(3, -1)) # 3행만 지정해주고 열에 -1을 넣으면 자동으로 배열을 reshape한다.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([1,0,1])
y = np.empty_like(a) # 배열 a와 크기가 같은 원소가 비어있는 배열 생성

# 배열 b를 a의 각 행에 더해주기 위해 반복문을 사용한다.
for i in range(3):
    y[i, : ] = a[i, : ] + b


print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [14]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([1,0,1])

c = a + b # c를 따로 선언 할 필요 없이 만들 수 있다.
print(c)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
