In [1]:
import numpy as np

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

sent = ("휴일 인 오늘 도 서쪽 을 중심 으로 폭염 이 이어졌는데요, 내일 은 반가운 비 소식 이 있습니다."\
        , "폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니 다.") 
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(sent) #문장 벡터화 진행

print(tfidf_matrix.toarray())
print()
print(sorted(tfidf_vectorizer.vocabulary_.items())) # 사전을 key별로 정렬(0부터 17까지 단어)
print()
idf = tfidf_vectorizer.idf_ # 각 단어의 idf값을 array로 저장
print(dict(zip(tfidf_vectorizer.get_feature_names_out(), idf))) 
# 각 단어의 이름과 그에 해당하는 idf 값을 튜플형태로 짝지어서 저장하고 사전 형태로 변환 (zip() 이용)

[[0.         0.3160305  0.         0.         0.3160305  0.3160305
  0.3160305  0.3160305  0.3160305  0.3160305  0.         0.
  0.3160305  0.3160305  0.2248583  0.         0.         0.2248583 ]
 [0.35327777 0.         0.35327777 0.35327777 0.         0.
  0.         0.         0.         0.         0.35327777 0.35327777
  0.         0.         0.25136004 0.35327777 0.35327777 0.25136004]]

[('갑작스런', 0), ('내일', 1), ('놀러왔다가', 2), ('망연자실', 3), ('반가운', 4), ('서쪽', 5), ('소식', 6), ('오늘', 7), ('으로', 8), ('이어졌는데요', 9), ('인해', 10), ('있습니', 11), ('있습니다', 12), ('중심', 13), ('폭염', 14), ('피해서', 15), ('하고', 16), ('휴일', 17)]

{'갑작스런': 1.4054651081081644, '내일': 1.4054651081081644, '놀러왔다가': 1.4054651081081644, '망연자실': 1.4054651081081644, '반가운': 1.4054651081081644, '서쪽': 1.4054651081081644, '소식': 1.4054651081081644, '오늘': 1.4054651081081644, '으로': 1.4054651081081644, '이어졌는데요': 1.4054651081081644, '인해': 1.4054651081081644, '있습니': 1.4054651081081644, '있습니다': 1.4054651081081644, '중심': 1.4054651081081644, '

## 자카드 유사도

In [26]:
sent = ("휴일 인 오늘 도 서쪽 을 중심 으로 폭염 이 이어졌는데요, 내일 은 반가운 비 소식 이 있습니다.", 
        "폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니다.") 
        
tokenized_doc1 = set(sent[0].split(' '))
tokenized_doc2 = set(sent[1].split(' '))

union =tokenized_doc1.union(tokenized_doc2)
print("합집합 = ", union)

intersection = tokenized_doc1.intersection(tokenized_doc2)
print("교집합 = ", intersection)

jaccardScore = len(intersection)/len(union)

print("자카드 유사도 = ", jaccardScore)

합집합 =  {'비', '갑작스런', '망연자실', '은', '있습니다.', '내일', '폭염', '이어졌는데요,', '에', '오늘', '인해', '피해서', '도', '휴일', '하고', '을', '로', '서쪽', '으로', '이', '놀러왔다가', '소식', '인', '반가운', '중심'}
교집합 =  {'휴일', '비', '을', '있습니다.', '폭염'}
자카드 유사도 =  0.2


## 코사인 유사도

In [30]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(tfidf_matrix[0], tfidf_matrix[1]) #첫번째 행과 둘째 행간의 유사도 

array([[0.11304078]])

## 유클리디안 유사도

In [31]:
from sklearn.metrics.pairwise import euclidean_distances

euclidean_distances(tfidf_matrix[0], tfidf_matrix[1])

array([[1.33188529]])

In [32]:
from sklearn.metrics.pairwise import euclidean_distances

euclidean_distances(tfidf_matrix[0], tfidf_matrix[1])


import numpy as np

def l1_normalize(v):
    norm = np.sum(v)
    return v / norm

tfidf_norm_l1 = l1_normalize(tfidf_matrix)
euclidean_distances(tfidf_norm_l1[0], tfidf_norm_l1[1])

array([[0.21243357]])

In [41]:
a= np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [43]:
b= np.sum(a)
print(a/b)

[[0.1 0.2]
 [0.3 0.4]]


## 맨해튼 유사도

In [44]:
from sklearn.metrics.pairwise import manhattan_distances

manhattan_distances(tfidf_norm_l1[0], tfidf_norm_l1[1])

array([[0.85654185]])