In [30]:
import tensorflow as tf
from tensorflow.keras import preprocessing
import numpy as np
from keras import layers

In [31]:
samples = ['너 오늘 이뻐 보인다',
          '나는 오늘 기분이 더러워',
          '끝내주는데, 좋은 일이 있나봐',
          '나 좋은 일이 생겼어',
          '아 오늘 진짜 짜증나',
          '환상적인데, 정말 좋은거 같아']

targets =[[1], [0], [1], [1], [0], [1]]

In [32]:
tokenizer = preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples)
print(sequences)
input_sequences = np.array(sequences)
print(input_sequences)
labels = np.array(targets)
print(labels)
word_index = tokenizer.word_index
print(word_index)

[[4, 1, 5, 6], [7, 1, 8, 9], [10, 2, 3, 11], [12, 2, 3, 13], [14, 1, 15, 16], [17, 18, 19, 20]]
[[ 4  1  5  6]
 [ 7  1  8  9]
 [10  2  3 11]
 [12  2  3 13]
 [14  1 15 16]
 [17 18 19 20]]
[[1]
 [0]
 [1]
 [1]
 [0]
 [1]]
{'오늘': 1, '좋은': 2, '일이': 3, '너': 4, '이뻐': 5, '보인다': 6, '나는': 7, '기분이': 8, '더러워': 9, '끝내주는데': 10, '있나봐': 11, '나': 12, '생겼어': 13, '아': 14, '진짜': 15, '짜증나': 16, '환상적인데': 17, '정말': 18, '좋은거': 19, '같아': 20}


batch_size = 2                      \
: 2개의 문장을 입력받을 때 마다, 가중치 업데이트\
num_epochs = 100                     \
: 총6개의 문장을 받아오는데 이걸 100번\
vocab_size = len(word_index) + 1     
: word_index라는 사전에 20개의 단어가 존재한다. but 0부터 시작하면 19에서 끝나므로, 1부터 시작하게 +1 더함 \
emb_size = 128\
: 각 단어의 임베딩 사이즈 : 128 차원의 임베딩으로 만든다\
hidden_dimension = 256\
: FC로 연결되는 내부 은닉층 노드 개수\
output_dimension = 1  
: 출력 1차원 => 0 or 1

In [36]:
batch_size = 2
num_epochs = 100
vocab_size = len(word_index) + 1
emb_size = 128
hidden_dimension = 256
output_dimension = 1

In [37]:
model = tf.keras.Sequential([
layers.Embedding(vocab_size, emb_size, input_length = 4),
layers.Lambda(lambda x: tf.reduce_mean(x, axis = 1)),
layers.Dense(hidden_dimension, activation='relu'),
layers.Dense(output_dimension, activation='sigmoid')])

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [38]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 4, 128)            2688      
                                                                 
 lambda_1 (Lambda)           (None, 128)               0         
                                                                 
 dense_10 (Dense)            (None, 256)               33024     
                                                                 
 dense_11 (Dense)            (None, 1)                 257       
                                                                 
Total params: 35,969
Trainable params: 35,969
Non-trainable params: 0
_________________________________________________________________


In [39]:
model.fit(input_sequences, labels, epochs=num_epochs, batch_size=batch_size)

Epoch 1/100
3/3 [==============================] - 1s 6ms/step - loss: 0.6936 - accuracy: 0.1667
Epoch 2/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6755 - accuracy: 1.0000
Epoch 3/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6620 - accuracy: 1.0000
Epoch 4/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6463 - accuracy: 1.0000
Epoch 5/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6286 - accuracy: 1.0000
Epoch 6/100
3/3 [==============================] - 0s 5ms/step - loss: 0.6096 - accuracy: 1.0000
Epoch 7/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5853 - accuracy: 1.0000
Epoch 8/100
3/3 [==============================] - 0s 5ms/step - loss: 0.5559 - accuracy: 1.0000
Epoch 9/100
3/3 [==============================] - 0s 2ms/step - loss: 0.5252 - accuracy: 1.0000
Epoch 10/100
3/3 [==============================] - 0s 9ms/step - loss: 0.4901 - accuracy: 1.0000
Epoch 11/100
3/3 [===========

In [40]:
test=["나 진짜 오늘 짜증나"]
seq=tokenizer.texts_to_sequences(test)
print(seq)

[[12, 15, 1, 16]]


In [41]:
model.predict(seq)

array([[0.01303047]], dtype=float32)

In [42]:
test=["나 진짜 오늘 이뻐"]
seq=tokenizer.texts_to_sequences(test)
print(seq)

[[12, 15, 1, 5]]


In [43]:
model.predict(seq)

array([[0.7331028]], dtype=float32)

## Functional API

In [7]:
import tensorflow as tf
from tensorflow.keras import preprocessing
import numpy as np
from keras import layers

In [8]:
samples = ['너 오늘 이뻐 보인다',
          '나는 오늘 기분이 더러워',
          '끝내주는데, 좋은 일이 있나봐',
          '나 좋은 일이 생겼어',
          '아 오늘 진짜 짜증나',
          '환상적인데, 정말 좋은거 같아']

targets =[[1], [0], [1], [1], [0], [1]]

tokenizer = preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples)
print(sequences)
input_sequences = np.array(sequences)
print(input_sequences)
labels = np.array(targets)
print(labels)
word_index = tokenizer.word_index
print(word_index)

[[4, 1, 5, 6], [7, 1, 8, 9], [10, 2, 3, 11], [12, 2, 3, 13], [14, 1, 15, 16], [17, 18, 19, 20]]
[[ 4  1  5  6]
 [ 7  1  8  9]
 [10  2  3 11]
 [12  2  3 13]
 [14  1 15 16]
 [17 18 19 20]]
[[1]
 [0]
 [1]
 [1]
 [0]
 [1]]
{'오늘': 1, '좋은': 2, '일이': 3, '너': 4, '이뻐': 5, '보인다': 6, '나는': 7, '기분이': 8, '더러워': 9, '끝내주는데': 10, '있나봐': 11, '나': 12, '생겼어': 13, '아': 14, '진짜': 15, '짜증나': 16, '환상적인데': 17, '정말': 18, '좋은거': 19, '같아': 20}


In [10]:
batch_size = 2
num_epochs = 100
vocab_size = len(word_index) + 1
emb_size = 128
hidden_dimension = 256
output_dimension = 1

In [11]:
inputs = layers.Input(shape = (4, ))
embed_output = layers.Embedding(vocab_size, emb_size)(inputs)
pooled_output = tf.reduce_mean(embed_output, axis=1)
hidden_layer = layers.Dense(hidden_dimension, activation='relu')(pooled_output)
outputs = layers.Dense(output_dimension, activation='sigmoid')(hidden_layer)

In [12]:
model = tf.keras.Model(inputs=inputs, outputs=outputs)

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [13]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 4)]               0         
                                                                 
 embedding (Embedding)       (None, 4, 128)            2688      
                                                                 
 tf.math.reduce_mean (TFOpLa  (None, 128)              0         
 mbda)                                                           
                                                                 
 dense (Dense)               (None, 256)               33024     
                                                                 
 dense_1 (Dense)             (None, 1)                 257       
                                                                 
Total params: 35,969
Trainable params: 35,969
Non-trainable params: 0
_________________________________________________________

In [14]:
model.fit(input_sequences, labels, epochs=num_epochs, batch_size=batch_size)

Epoch 1/100
3/3 [==============================] - 1s 4ms/step - loss: 0.6980 - accuracy: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6796 - accuracy: 1.0000
Epoch 3/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6646 - accuracy: 1.0000
Epoch 4/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6497 - accuracy: 1.0000
Epoch 5/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6325 - accuracy: 1.0000
Epoch 6/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6120 - accuracy: 1.0000
Epoch 7/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5891 - accuracy: 1.0000
Epoch 8/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5591 - accuracy: 1.0000
Epoch 9/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5251 - accuracy: 1.0000
Epoch 10/100
3/3 [==============================] - 0s 2ms/step - loss: 0.4877 - accuracy: 1.0000
Epoch 11/100
3/3 [=======

### test

In [15]:
test=["나 진짜 오늘 짜증나"]
seq=tokenizer.texts_to_sequences(test)
print(seq)

model.predict(seq)

[[12, 15, 1, 16]]


array([[0.00917354]], dtype=float32)

In [16]:
test=["나 진짜 오늘 이뻐"]
seq=tokenizer.texts_to_sequences(test)
print(seq)

model.predict(seq)

[[12, 15, 1, 5]]


array([[0.7162025]], dtype=float32)

## Subclassing

In [23]:
class CustomModel(tf.keras.Model):

    def __init__(self, vocab_size, embed_dimension, hidden_dimension, output_dimension):
        super(CustomModel, self).__init__(name='my_model')
        self.embedding = layers.Embedding(vocab_size, embed_dimension)
        self.dense_layer = layers.Dense(hidden_dimension, activation='relu')
        self.output_layer = layers.Dense(output_dimension, activation='sigmoid')

    def call(self, inputs):
        x = self.embedding(inputs)
        x = tf.reduce_mean(x, axis=1)
        x = self.dense_layer(x)
        x = self.output_layer(x)
        
        return x

In [24]:
model = CustomModel(vocab_size = vocab_size,
            embed_dimension=emb_size,
            hidden_dimension=hidden_dimension,
            output_dimension=output_dimension)

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [26]:
## model.summary를 하려면 build() 메소드가 있어야 한다. 하지만 subclasssing에서 build()를 만들이 않아서 사용 불가

In [27]:
model.fit(input_sequences, labels, epochs=num_epochs, batch_size=batch_size)

Epoch 1/100
3/3 [==============================] - 0s 2ms/step - loss: 0.6916 - accuracy: 0.6667
Epoch 2/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6720 - accuracy: 1.0000
Epoch 3/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6560 - accuracy: 1.0000
Epoch 4/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6385 - accuracy: 1.0000
Epoch 5/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6191 - accuracy: 1.0000
Epoch 6/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5967 - accuracy: 1.0000
Epoch 7/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5698 - accuracy: 1.0000
Epoch 8/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5386 - accuracy: 1.0000
Epoch 9/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5040 - accuracy: 1.0000
Epoch 10/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4622 - accuracy: 1.0000
Epoch 11/100
3/3 [===========

### test

In [28]:
test=["나 진짜 오늘 짜증나"]
seq=tokenizer.texts_to_sequences(test)
print(seq)

model.predict(seq)

[[12, 15, 1, 16]]


array([[0.01804432]], dtype=float32)

In [29]:
test=["나 진짜 오늘 이뻐"]
seq=tokenizer.texts_to_sequences(test)
print(seq)

model.predict(seq)

[[12, 15, 1, 5]]


array([[0.79299825]], dtype=float32)