<a href="https://colab.research.google.com/github/DonghaeSuh/NLP_tensorflow2/blob/main/layers_GlobalMaxPooling1D()_tf_concat()_ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import tensorflow as tf
import numpy as np

In [41]:
x=np.array([[1.,2.,3.,4.,5.],[6.,7.,8.,9.,10.]])
x=x.T
x=np.reshape(x,[1,5,2])
x

array([[[ 1.,  6.],
        [ 2.,  7.],
        [ 3.,  8.],
        [ 4.,  9.],
        [ 5., 10.]]])

In [42]:
max_pool_1d = tf.keras.layers.GlobalMaxPooling1D()
max_pool_1d(x)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 5., 10.]], dtype=float32)>

In [43]:
a=tf.concat([[[1,2,3]],[[4,5,6]],[[7,8,9]]],axis=-1)
a

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)>