<a href="https://colab.research.google.com/github/DonghaeSuh/NLP_tensorflow2/blob/main/6_ChatBot/Transformer_ChatBot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [7]:
b=1-tf.linalg.band_part(tf.ones((2,2)),-1,0)

In [10]:
b*-1e9

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.e+00, -1.e+09],
       [-0.e+00, -0.e+00]], dtype=float32)>

In [5]:
import numpy as np

In [6]:
a=np.array([[1,2],[3,4]])

In [11]:
a+=b*-1e9

In [12]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.e+00, -1.e+09],
       [ 3.e+00,  4.e+00]], dtype=float32)>

In [13]:
a=np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[1,2],[3,4]],[[5,6],[7,8]]]])

In [14]:
a.shape

(2, 2, 2, 2)

In [15]:
tf.matmul(a,a)

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[  7,  10],
         [ 15,  22]],

        [[ 67,  78],
         [ 91, 106]]],


       [[[  7,  10],
         [ 15,  22]],

        [[ 67,  78],
         [ 91, 106]]]])>