<a href="https://colab.research.google.com/github/DonghaeSuh/NLP_tensorflow2/blob/main/6_ChatBot/Transformer_ChatBot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [ ]:
b=1-tf.linalg.band_part(tf.ones((2,2)),-1,0)

In [ ]:
b*-1e9

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.e+00, -1.e+09],
       [-0.e+00, -0.e+00]], dtype=float32)>

In [2]:
import numpy as np

In [ ]:
a=np.array([[1,2],[3,4]])

In [ ]:
a+=b*-1e9

In [ ]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.e+00, -1.e+09],
       [ 3.e+00,  4.e+00]], dtype=float32)>

In [ ]:
a=np.array([[[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]],[[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]]])

In [ ]:
a.shape

(2, 2, 2, 3)

In [ ]:
tf.matmul(a,a,transpose_b=True)

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 14,  26],
         [ 26,  50]],

        [[110, 146],
         [146, 194]]],


       [[[ 14,  26],
         [ 26,  50]],

        [[110, 146],
         [146, 194]]]])>

### tf.reshape & tf.transpose  (4차원)

In [8]:
a = np.array([[[1,2,3,4],[4,5,6,7]],[[7,8,9,10],[10,11,12,13]]])
a

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7]],

       [[ 7,  8,  9, 10],
        [10, 11, 12, 13]]])

In [9]:
b=tf.reshape(a,(2,-1,2,2))
b

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 7,  8],
         [ 9, 10]],

        [[10, 11],
         [12, 13]]]])>

In [10]:
tf.transpose(b) # perm = [3,2,1,0]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  7],
         [ 4, 10]],

        [[ 3,  9],
         [ 6, 12]]],


       [[[ 2,  8],
         [ 5, 11]],

        [[ 4, 10],
         [ 7, 13]]]])>

In [ ]:
tf.transpose(b,[0,2,1,3])

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  2],
         [ 4,  5]],

        [[ 3,  4],
         [ 6,  7]]],


       [[[ 7,  8],
         [10, 11]],

        [[ 9, 10],
         [12, 13]]]])>

In [ ]:
tf.transpose(b,[3,1,2,0])

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  7],
         [ 3,  9]],

        [[ 4, 10],
         [ 6, 12]]],


       [[[ 2,  8],
         [ 4, 10]],

        [[ 5, 11],
         [ 7, 13]]]])>

In [ ]:
tf.reshape(a,(2,2,-1,2))

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 7,  8],
         [ 9, 10]],

        [[10, 11],
         [12, 13]]]])>

In [3]:
x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])

In [7]:
x

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [4]:
tf.transpose(x) #perm=[2,1,0]

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]], dtype=int32)>

In [5]:
tf.transpose(x,perm=[1,2,0])

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]], dtype=int32)>

In [6]:
tf.transpose(x,perm=[2,0,1])

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  4],
        [ 7, 10]],

       [[ 2,  5],
        [ 8, 11]],

       [[ 3,  6],
        [ 9, 12]]], dtype=int32)>

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
tf.transpose(a) # perm = [1,0]

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

perm의 해당 차원(axis)에 따른 연산 횟수(이어붙이기)가, 새로 만들어지는 행렬의 행 차원이 될 것이므로, 현재 차원이 perm의 위치에 따라 적절하게 변하다.

perm의 마지막 axis부터 차례대로 뒷 차원부터 쌓여서 결과가 나올텐데,
각 차원에 해당하는 이어붙이기 개수가 그 차워의 개수가 될 것이므로,\
차원이 우리가 원하는 대로 변형된다.